"""Generate the citelint HTML page."""

import json
import re

from citelint.parser import build_urls, clean_latex, extract_url, format_authors

_STRINGS = {
    "en": dict(
        pt="citelint", sub="Generated by citelint",
        refs="references",
        bo="Passed", bw="Warnings", bf="Errors", orp="Uncited",
        se="Search by key, title, or author...",
        fa="All", ff="Errors", fw="Warnings", fk="Passed", fo="Uncited",
        pr="PDF RENDERED REFERENCE (what reviewer sees)",
        fd="ENTRY FIELDS", cx="CITATION CONTEXTS",
        vl="QUICK SEARCH", bc="BIBGUARD CHECKS",
        ob="UNCITED", om="Not cited in any .tex file", np="(Not in PDF)",
        sr="SEARCH & VERIFY", srb="Search",
        tp="Type", au="Author", ti="Title", ve="Venue", yr="Year",
        pg="Pages", ci=" citations", ur="URL",
        tl="Title", al="Authors", vl2="Venue",
        fr="Reviewed", fu="Unreviewed", rv="MANUAL REVIEW",
        rvp="Passed", rvw="Warning", rve="Error",
        rvn="note (optional)", rvs="Submit", rvd="Delete",
        rvdc="Confirm delete?", rvx="Export reviewed (Markdown)",
    ),
    "zh": dict(
        pt="citelint", sub="由 citelint 生成",
        refs="条引用",
        bo="通过", bw="警告", bf="错误", orp="未引用",
        se="搜索 key、标题或作者...",
        fa="全部", ff="错误", fw="警告", fk="通过", fo="未引用",
        pr="PDF 渲染原文（审稿人实际看到的）",
        fd="条目字段", cx="引用上下文",
        vl="快捷搜索", bc="BIBGUARD 检查",
        ob="未引用", om="未被任何 .tex 文件引用", np="（不在 PDF 中）",
        sr="检索验证", srb="检索",
        tp="类型", au="作者", ti="标题", ve="发表场所", yr="年份",
        pg="页码", ci=" 次引用", ur="URL",
        tl="标题", al="作者", vl2="发表",
        fr="已审阅", fu="未审阅", rv="人工审阅",
        rvp="通过", rvw="警告", rve="错误",
        rvn="备注（可选）", rvs="提交", rvd="删除",
        rvdc="确认删除？", rvx="导出审阅（Markdown）",
    ),
}


def esc(s):
    """HTML escape for display text."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def generate_html(bib_entries, bbl_order, bbl_entries, contexts, bg_data, orphan_keys, lang="en", has_s2_key=False, paper_title=""):
    """Generate the full HTML audit page."""
    L = _STRINGS[lang]

    bg_map = {}
    bg_pending = bg_data is None
    if bg_data:
        bg_map = {r["key"]: r for r in bg_data.get("results", [])}

    stats = {"ok": 0, "warn": 0, "fail": 0}
    for k in bib_entries:
        r = bg_map.get(k)
        if r:
            o = r["overall"]
            if o == "OK":
                stats["ok"] += 1
            elif o == "WARN":
                stats["warn"] += 1
            elif o == "FAIL":
                stats["fail"] += 1

    ordered = list(bbl_order)
    for k in sorted(bib_entries.keys()):
        if k not in ordered:
            ordered.append(k)
    total = len(bib_entries)
    kn = {k: i + 1 for i, k in enumerate(bbl_order)}

    bib_json = {}
    for key, fields in bib_entries.items():
        bib_json[key] = {
            "title": clean_latex(fields.get("title", "")),
            "year": fields.get("year", ""),
        }

    cards = []
    for key in ordered:
        if key not in bib_entries:
            continue
        f = bib_entries[key]
        bg_r = bg_map.get(key)
        sc, si = "unknown", "—"
        if bg_r:
            o = bg_r["overall"]
            if o == "OK":
                sc, si = "ok", "✓"
            elif o == "WARN":
                sc, si = "warn", "!"
            elif o == "FAIL":
                sc, si = "fail", "✗"
        io = key in orphan_keys
        ctxs = contexts.get(key, [])
        bt = bbl_entries.get(key, "")
        pn = kn.get(key)
        ti = clean_latex(f.get("title", "N/A"))
        au = format_authors(f.get("author", "N/A"))
        yr = f.get("year", "N/A")
        ve = clean_latex(f.get("booktitle", "") or f.get("journal", "") or "")
        pg = f.get("pages", "")
        et = f.get("_type", "")
        url_val = extract_url(f)
        if url_val:
            safe_url = url_val.replace("'", "\\'")
            url_display = esc(url_val[:60]) + ("..." if len(url_val) > 60 else "")
            url_cell = f'<a class="vl" onclick="openSide(\'{safe_url}\')" style="padding:2px 8px;font-size:11px">{url_display} ↗</a>'
        else:
            url_cell = '<span class="mi">—</span>'

        ch = ""
        if bg_r:
            for c in bg_r.get("checks", []):
                cs = c.get("status", "")
                ic = "✓" if cs == "OK" else "✗" if cs == "FAIL" else "!"
                ch += f'<div class="ci {cs.lower()}">{ic} <b>{esc(c.get("field", ""))}</b>: {esc(c.get("detail", ""))}</div>'

        urls = build_urls(key, f)
        ub = ""
        for label, url in urls:
            safe_url = url.replace("'", "\\'")
            ub += f'''<a class="vl" onclick="openSide('{safe_url}')">{esc(label)} ↗</a>'''

        cx = ""
        if ctxs:
            for fn, ln, ct in ctxs[:6]:
                ct_h = esc(ct).replace("★THIS★", '<mark class="tr">⟵ THIS REF</mark>')
                cx += f'<div class="cx"><span class="cl">{esc(fn)}:{ln}</span> {ct_h}</div>'
            if len(ctxs) > 6:
                cx += f'<div class="cm">... +{len(ctxs) - 6}</div>'
        else:
            cx = f'<div class="co">{L["om"]}</div>'

        pd = f'[{pn}] {esc(bt)}' if bt else f'<span class="mi">{L["np"]}</span>'
        ob = f' <span class="ob">{L["ob"]}</span>' if io else ""
        pl = f"[{pn}]" if pn else "—"

        cards.append(f'''<div class="rc {sc}" id="r-{key}" data-o="{1 if io else 0}" data-key="{key}">
<div class="rh" onclick="toggle(this.parentElement)">
<span class="ri">{pl}</span><span class="rs {sc}">{si}</span><span id="rvb-{key}"></span><span class="rk"><code>{key}</code></span>
<span class="rt">{esc(ti[:80])}{"..." if len(ti) > 80 else ""}</span>
<span class="rm">{esc(et)}·{esc(yr)}</span>{ob}
<span class="rn">{len(ctxs)}{L["ci"]}</span><span class="ei">▶</span></div>
<div class="rb"><div class="rc2">
<div class="rl">
<div class="sl">{L["pr"]}</div><div class="br">{pd}</div>
<div class="sl">{L["fd"]}</div>
<table class="ft"><tr><td class="fl">{L["tp"]}</td><td><code>@{esc(et)}</code></td></tr>
<tr><td class="fl">{L["au"]}</td><td>{esc(au)}</td></tr>
<tr><td class="fl">{L["ti"]}</td><td>{esc(ti)}</td></tr>
<tr><td class="fl">{L["ve"]}</td><td>{esc(ve) if ve else '<span class="mi">—</span>'}</td></tr>
<tr><td class="fl">{L["yr"]}</td><td>{esc(yr)}</td></tr>
<tr><td class="fl">{L["pg"]}</td><td>{esc(pg) if pg else '<span class="mi">—</span>'}</td></tr>
<tr><td class="fl">{L["ur"]}</td><td>{url_cell}</td></tr></table>
<div class="sl">{L["cx"]}</div><div class="cxl">{cx}</div></div>
<div class="rr">
<div class="sl">{L["vl"]}</div><div class="vls">{ub}</div>
<div class="sl">{L["bc"]}</div><div class="bgc">{ch if ch else '<span class="mi">—</span>'}</div>
<div class="sl">{L["sr"]}</div>
<div class="sr" id="sr-{key}"><button class="srb" onclick="search('{key}')">{L["srb"]}</button></div>
</div>
<div class="rv-section" id="rv-{key}"></div>
</div></div></div>''')

    return f'''<!DOCTYPE html><html lang="{lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{L["pt"]}{(' — ' + esc(paper_title)) if paper_title else ''}</title>
<style>
:root{{--bg:#0d1117;--sf:#161b22;--bd:#30363d;--tx:#e6edf3;--t2:#8b949e;--t3:#484f58;--ok:#238636;--wn:#d29922;--wnb:#1a1604;--fl:#f85149;--bl:#58a6ff;--pu:#bc8cff}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;background:var(--bg);color:var(--tx);padding:20px;line-height:1.5}}
.db{{max-width:1200px;margin:0 auto}}.pt{{font-size:22px;margin-bottom:4px;font-weight:600;line-height:1.3}}.sb{{color:var(--t2);margin-bottom:20px;font-size:13px}}.sb-brand{{color:var(--pu);font-weight:600;font-family:monospace;letter-spacing:.5px}}
.st{{display:flex;gap:12px;margin-bottom:20px;flex-wrap:wrap}}.s{{padding:12px 20px;border-radius:8px;border:1px solid var(--bd);background:var(--sf)}}
.sn{{font-size:28px;font-weight:bold}}.sl2{{font-size:12px;color:var(--t2)}}.so .sn{{color:var(--ok)}}.sw .sn{{color:var(--wn)}}.sf .sn{{color:var(--fl)}}
.fs{{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap}}.fb{{padding:6px 14px;border-radius:6px;border:1px solid var(--bd);background:var(--sf);color:var(--tx);cursor:pointer;font-size:13px}}
.fb:hover{{border-color:var(--bl)}}.fb.a{{background:var(--bl);color:#fff;border-color:var(--bl)}}
.rc{{border:1px solid var(--bd);border-radius:8px;margin-bottom:8px;overflow:hidden;background:var(--sf)}}
.rc.fail{{border-left:3px solid var(--fl)}}.rc.warn{{border-left:3px solid var(--wn)}}.rc.ok{{border-left:3px solid var(--ok)}}
.rh{{display:flex;align-items:center;gap:10px;padding:10px 16px;cursor:pointer;font-size:13px;flex-wrap:wrap}}.rh:hover{{background:rgba(255,255,255,.03)}}
.ri{{color:var(--bl);min-width:30px;font-weight:bold;font-family:monospace}}.rs{{font-size:14px;font-weight:bold;min-width:16px;text-align:center}}.rs.ok{{color:var(--ok)}}.rs.warn{{color:var(--wn)}}.rs.fail{{color:var(--fl)}}.rk{{font-size:12px;color:var(--pu)}}
.rt{{flex:1;min-width:200px;font-weight:500}}.rm,.rn{{color:var(--t2);font-size:11px;white-space:nowrap}}
.ei{{color:var(--t3);transition:transform .2s}}.rc.ex .ei{{transform:rotate(90deg)}}
.ob{{background:var(--wn);color:#000;font-size:10px;padding:1px 6px;border-radius:4px;font-weight:bold}}
.rb{{display:none;padding:16px;border-top:1px solid var(--bd)}}.rc.ex .rb{{display:block}}
.rc2{{display:grid;grid-template-columns:1fr 1fr;gap:24px}}@media(max-width:900px){{.rc2{{grid-template-columns:1fr}}}}
.sl{{font-size:12px;font-weight:600;color:var(--t2);margin:16px 0 6px;text-transform:uppercase;letter-spacing:.5px}}.sl:first-child{{margin-top:0}}
.br{{background:#1c2128;padding:12px;border-radius:6px;font-size:13px;line-height:1.6;border:1px solid var(--bd);color:#d2a8ff}}
.ft{{width:100%;font-size:13px}}.ft td{{padding:3px 8px;border-bottom:1px solid var(--bd);vertical-align:top}}.fl{{color:var(--t2);width:70px;font-weight:500;white-space:nowrap}}.mi{{color:var(--t3);font-style:italic}}
.cxl{{font-size:12px}}.cx{{padding:6px 8px;border-left:2px solid var(--bd);margin-bottom:4px;background:rgba(255,255,255,.02)}}
.cl{{color:var(--bl);font-family:monospace;font-size:11px;display:block;margin-bottom:2px}}
.co{{color:var(--wn);font-weight:500;padding:8px;background:var(--wnb);border-radius:4px}}.cm{{color:var(--t3);font-style:italic;padding:4px 8px}}
mark.tr{{background:#f0883e;color:#000;padding:1px 4px;border-radius:3px;font-weight:bold;font-size:11px}}
.vls{{display:flex;flex-wrap:wrap;gap:6px}}.vl{{display:inline-block;padding:5px 12px;border-radius:6px;border:1px solid var(--bd);color:var(--bl);text-decoration:none;font-size:12px;white-space:nowrap;cursor:pointer}}.vl:hover{{background:rgba(88,166,255,.1);border-color:var(--bl)}}
.bgc{{font-size:12px}}.ci{{padding:4px 0}}.ci.fail{{color:var(--fl)}}.ci.warn{{color:var(--wn)}}.ci.ok{{color:var(--tx)}}
.sr{{font-size:12px}}
.srb{{padding:6px 16px;border-radius:6px;border:1px solid var(--bl);background:rgba(88,166,255,.1);color:var(--bl);cursor:pointer;font-size:13px;font-weight:500}}.srb:hover{{background:rgba(88,166,255,.2)}}
.sr-box{{margin-top:8px}}.sr-src{{font-size:10px;color:var(--t3);text-transform:uppercase;letter-spacing:1px;margin:8px 0 4px;padding-top:8px;border-top:1px solid var(--bd)}}.sr-src:first-child{{border-top:none;padding-top:0}}
.sr-item{{background:#1c2128;padding:8px 10px;border-radius:6px;border:1px solid var(--bd);margin-bottom:4px;position:relative}}
.sr-item .x{{position:absolute;top:4px;right:8px;color:var(--t3);cursor:pointer;font-size:14px}}.sr-item .x:hover{{color:var(--fl)}}
.sr-t{{color:var(--ok);font-weight:bold;font-size:12px;padding-right:20px}}.sr-a{{color:var(--t2);font-size:11px;margin:2px 0}}
.sr-v{{color:var(--pu);font-size:11px}}.sr-ab{{color:var(--t2);font-size:11px;margin-top:4px;line-height:1.4}}
.sr-c{{font-size:10px;margin-bottom:2px}}.sr-c.high{{color:var(--ok)}}.sr-c.med{{color:var(--wn)}}.sr-c.low{{color:var(--fl)}}
.sr-l{{margin-top:4px;display:flex;gap:4px;flex-wrap:wrap}}
.sr-l a{{color:var(--bl);font-size:10px;text-decoration:none;padding:1px 6px;border:1px solid var(--bd);border-radius:3px;cursor:pointer}}.sr-l a:hover{{border-color:var(--bl)}}
.sr-e{{color:var(--fl);font-size:12px;margin-top:4px}}
.sr-lb{{color:var(--t3);font-weight:normal;font-size:10px;margin-right:6px;text-transform:uppercase}}
.hd{{display:none!important}}
.sx{{width:100%;padding:8px 12px;border-radius:6px;border:1px solid var(--bd);background:var(--sf);color:var(--tx);font-size:14px;margin-bottom:12px}}.sx::placeholder{{color:var(--t3)}}
.kb{{padding:12px 16px;border-radius:8px;border:1px solid var(--wn);background:rgba(210,153,34,.08);margin-bottom:16px;font-size:13px;line-height:1.6}}
.kb.ok{{border-color:var(--ok);background:rgba(35,134,54,.08)}}.kb b{{color:var(--wn)}}.kb.ok b{{color:var(--ok)}}
.kb input{{padding:4px 8px;border-radius:4px;border:1px solid var(--bd);background:var(--sf);color:var(--tx);font-size:13px;width:320px;margin:0 6px;font-family:monospace}}
.kb button{{padding:4px 12px;border-radius:4px;border:1px solid var(--bl);background:rgba(88,166,255,.1);color:var(--bl);cursor:pointer;font-size:12px}}.kb button:hover{{background:rgba(88,166,255,.2)}}
.kb a{{color:var(--bl);text-decoration:none}}.kb a:hover{{text-decoration:underline}}
.kb .kd{{color:var(--t2);font-size:11px;margin-top:6px}}
.sp{{display:inline-block;width:14px;height:14px;border:2px solid var(--t3);border-top-color:var(--wn);border-radius:50%;animation:spin .8s linear infinite;vertical-align:middle;margin-right:6px}}
@keyframes spin{{to{{transform:rotate(360deg)}}}}
.rv-badge{{font-size:11px;padding:1px 7px;border-radius:10px;font-weight:600;margin-left:4px;vertical-align:middle}}
.rv-badge.rv-passed{{color:var(--ok);border:1.5px solid var(--ok);background:rgba(35,134,54,.1)}}
.rv-badge.rv-warning{{color:var(--wn);border:1.5px solid var(--wn);background:rgba(210,153,34,.1)}}
.rv-badge.rv-error{{color:var(--fl);border:1.5px solid var(--fl);background:rgba(248,81,73,.1)}}
.rv-section{{border-top:1px dashed var(--bd);margin-top:16px;padding-top:12px;grid-column:1/-1}}
.rv-label{{font-size:12px;font-weight:600;color:var(--t2);text-transform:uppercase;letter-spacing:.5px;margin-bottom:8px}}
.rv-form{{display:flex;gap:8px;align-items:center;flex-wrap:wrap}}
.rv-select{{padding:5px 10px;border-radius:6px;border:1px solid var(--bd);background:var(--bg);color:var(--tx);font-size:13px;cursor:pointer}}
.rv-select option[value=passed]{{color:var(--ok)}}.rv-select option[value=warning]{{color:var(--wn)}}.rv-select option[value=error]{{color:var(--fl)}}
.rv-select.s-passed{{border-color:var(--ok);color:var(--ok)}}.rv-select.s-warning{{border-color:var(--wn);color:var(--wn)}}.rv-select.s-error{{border-color:var(--fl);color:var(--fl)}}
.rv-input{{flex:1;min-width:200px;padding:5px 10px;border-radius:6px;border:1px solid var(--bd);background:var(--bg);color:var(--tx);font-size:13px}}
.rv-input::placeholder{{color:var(--t3)}}
.rv-submit{{padding:5px 14px;border-radius:6px;border:1px solid var(--ok);background:rgba(35,134,54,.15);color:var(--ok);cursor:pointer;font-size:13px;font-weight:500}}.rv-submit:hover{{background:rgba(35,134,54,.25)}}
.rv-existing{{display:flex;align-items:center;gap:8px;font-size:13px;flex-wrap:wrap}}
.rv-existing .rv-note{{color:var(--t2);font-style:italic}}
.rv-existing .rv-time{{color:var(--t3);font-size:11px}}
.rv-edit{{padding:3px 10px;border-radius:6px;border:1px solid var(--bl);background:rgba(88,166,255,.1);color:var(--bl);cursor:pointer;font-size:11px}}.rv-edit:hover{{background:rgba(88,166,255,.2)}}
.rv-del{{padding:3px 10px;border-radius:6px;border:1px solid var(--fl);background:rgba(248,81,73,.1);color:var(--fl);cursor:pointer;font-size:11px}}.rv-del:hover{{background:rgba(248,81,73,.2)}}
.rv-del.rv-confirm{{background:rgba(248,81,73,.3);border-color:var(--fl);font-weight:bold}}
.export-btn{{padding:5px 12px;border-radius:6px;border:1px solid var(--bd);background:var(--sf);color:var(--t2);cursor:pointer;font-size:12px;margin-left:auto}}.export-btn:hover{{border-color:var(--bl);color:var(--bl)}}
</style></head><body>
<div class="db">{('<h1 class="pt">' + esc(paper_title) + '</h1>') if paper_title else ''}<div class="sb"><span class="sb-brand">{L["pt"]}</span> · {total} {L["refs"]}</div>
<div class="kb" id="kb"></div>
<div id="bg-banner" class="kb" style="display:none;font-size:13px"></div>
<div class="st">
<div class="s so"><div class="sn">{stats["ok"]}</div><div class="sl2">{L["bo"]}</div></div>
<div class="s sw"><div class="sn">{stats["warn"]}</div><div class="sl2">{L["bw"]}</div></div>
<div class="s sf"><div class="sn">{stats["fail"]}</div><div class="sl2">{L["bf"]}</div></div>
<div class="s"><div class="sn">{len(orphan_keys)}</div><div class="sl2">{L["orp"]}</div></div></div>
<input class="sx" id="sq" placeholder="{L["se"]}" oninput="fc()">
<div class="fs">
<button class="fb a" onclick="sf('all',this)">{L["fa"]} ({total})</button>
<button class="fb" onclick="sf('fail',this)">{L["ff"]} ({stats["fail"]})</button>
<button class="fb" onclick="sf('warn',this)">{L["fw"]} ({stats["warn"]})</button>
<button class="fb" onclick="sf('ok',this)">{L["fk"]} ({stats["ok"]})</button>
<button class="fb" onclick="sf('orphan',this)">{L["fo"]} ({len(orphan_keys)})</button>
<button class="fb" onclick="sf('reviewed',this)" id="fb-reviewed">{L["fr"]} (0)</button>
<button class="fb" onclick="sf('unreviewed',this)" id="fb-unreviewed">{L["fu"]} ({total})</button>
<button class="export-btn" onclick="exportReviews()">{L["rvx"]}</button></div>
<div id="rl">{"".join(cards)}</div>
</div>
<script>
const B={json.dumps(bib_json, ensure_ascii=False)};
let sw=null;
function toggle(c){{c.classList.toggle('ex');}}
function openSide(url){{
  const w=650,h=window.innerHeight,l=window.screenX+window.outerWidth,t=window.screenY;
  if(sw&&!sw.closed){{sw.location.href=url;sw.focus();}}
  else{{sw=window.open(url,'aside','width='+w+',height='+h+',left='+l+',top='+t+',scrollbars=yes,resizable=yes');}}
}}
function score(bt,at,by,ay){{
  const bw=new Set(bt.toLowerCase().match(/\\w+/g)||[]);
  const aw=new Set(at.toLowerCase().match(/\\w+/g)||[]);
  let s=[...bw].filter(w=>aw.has(w)).length/Math.max(bw.size,aw.size);
  if(by===ay)s+=0.1;return s;
}}
async function search(key){{
  const el=document.getElementById('sr-'+key);
  const d=B[key];if(!d)return;
  el.innerHTML='<span style="color:var(--t2)">Searching...</span>';
  const enc=encodeURIComponent(d.title);
  const [sR,dR]=await Promise.allSettled([
    fetch('/api/s2?query='+enc+'&limit=3&fields=title,authors,year,venue,abstract,tldr,externalIds,url').then(r=>r.json()),
    fetch('/api/dblp?q='+enc+'&format=json&h=3').then(r=>r.json())
  ]);
  let h='<div class="sr-box">';
  let bestMatch=null;
  h+='<div class="sr-src">Semantic Scholar</div>';
  if(sR.status==='fulfilled'&&!sR.value.error){{
    const papers=sR.value.data||[];
    if(papers.length){{for(const p of papers){{
      const t=p.title||'',au=(p.authors||[]).map(x=>x.name).join(' / ');
      const sc=score(d.title,t,d.year,String(p.year||'')),pct=(sc*100).toFixed(0);
      const cls=sc>0.85?'high':sc>0.6?'med':'low';const ext=p.externalIds||{{}};
      const tldr=p.tldr?.text||'';const ab=tldr||(p.abstract||'').slice(0,250)+(p.abstract?.length>250?'...':'');
      let lk='';if(p.url)lk+=`<a onclick="openSide('${{p.url}}')">S2</a>`;
      if(ext.DOI)lk+=`<a onclick="openSide('https://doi.org/${{ext.DOI}}')">DOI</a>`;
      if(ext.ArXiv)lk+=`<a onclick="openSide('https://arxiv.org/abs/${{ext.ArXiv}}')">arXiv</a>`;
      h+=`<div class="sr-item"><span class="x" onclick="this.parentElement.remove()">x</span>
        <div class="sr-c ${{cls}}">Match: ${{pct}}%</div>
        <div class="sr-t"><span class="sr-lb">{L["tl"]}</span>${{t}}</div>
        <div class="sr-a"><span class="sr-lb">{L["al"]}</span>${{au}}</div>
        <div class="sr-v"><span class="sr-lb">{L["vl2"]}</span>${{p.venue||''}} ${{p.year||''}}</div>
        ${{ab?'<div class="sr-ab">'+(tldr?'<b>TLDR:</b> ':'')+ab+'</div>':''}}<div class="sr-l">${{lk}}</div></div>`;
      if(parseInt(pct)>=100&&(!bestMatch||parseInt(pct)>bestMatch.match))bestMatch={{source:'Semantic Scholar',title:t,authors:au,venue:p.venue||'',year:String(p.year||''),url:p.url||'',match:parseInt(pct)}};
    }}}} else h+='<div class="sr-e">No results</div>';
  }} else {{ const err=sR.value?.error||sR.reason||'Error';
    h+=`<div class="sr-e">S2: ${{err}}</div>`; }}
  h+='<div class="sr-src">DBLP</div>';
  if(dR.status==='fulfilled'&&!dR.value.error){{
    const hits=dR.value.result?.hits?.hit||[];
    if(hits.length){{for(const hi of hits){{
      const i=hi.info||{{}};const t=(i.title||'').replace(/\\.$/,'');
      const aus=i.authors?.author||[];const aL=Array.isArray(aus)?aus:[aus];
      const a=aL.map(x=>x.text||x).join(' / ');
      const sc=score(d.title,t,d.year,i.year||''),pct=(sc*100).toFixed(0);
      const cls=sc>0.85?'high':sc>0.6?'med':'low';
      let lk='';if(i.url)lk+=`<a onclick="openSide('${{i.url}}')">DBLP</a>`;
      if(i.doi)lk+=`<a onclick="openSide('https://doi.org/${{i.doi}}')">DOI</a>`;
      if(i.ee)lk+=`<a onclick="openSide('${{i.ee}}')">Publisher</a>`;
      h+=`<div class="sr-item"><span class="x" onclick="this.parentElement.remove()">x</span>
        <div class="sr-c ${{cls}}">Match: ${{pct}}%</div>
        <div class="sr-t"><span class="sr-lb">{L["tl"]}</span>${{t}}</div>
        <div class="sr-a"><span class="sr-lb">{L["al"]}</span>${{a}}</div>
        <div class="sr-v"><span class="sr-lb">{L["vl2"]}</span>${{i.venue||''}} ${{i.year||''}}</div>
        <div class="sr-l">${{lk}}</div></div>`;
      if(parseInt(pct)>=100&&(!bestMatch||parseInt(pct)>bestMatch.match))bestMatch={{source:'DBLP',title:t,authors:a,venue:i.venue||'',year:i.year||'',url:i.url||i.ee||'',match:parseInt(pct)}};
    }}}} else h+='<div class="sr-e">No results</div>';
  }} else h+=`<div class="sr-e">DBLP: ${{dR.value?.error||dR.reason||'Error'}}</div>`;
  if(bestMatch)fetch('/api/search-cache',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify(Object.assign({{key:key}},bestMatch))}});
  h+='</div>';el.innerHTML=h;
}}
let cf='all';
function sf(f,b){{cf=f;document.querySelectorAll('.fb').forEach(x=>x.classList.remove('a'));b.classList.add('a');fc();}}
function fc(){{const q=document.getElementById('sq').value.toLowerCase();document.querySelectorAll('.rc').forEach(c=>{{
  const t=c.textContent.toLowerCase(),ms=!q||t.includes(q);let mf=true;
  if(cf==='fail')mf=c.classList.contains('fail');else if(cf==='warn')mf=c.classList.contains('warn');
  else if(cf==='ok')mf=c.classList.contains('ok');else if(cf==='orphan')mf=c.dataset.o==='1';
  else if(cf==='reviewed')mf=c.dataset.reviewed==='1';else if(cf==='unreviewed')mf=c.dataset.reviewed!=='1';
  c.classList.toggle('hd',!(ms&&mf));}});}}
// ── Review system ──
const _rvL={{rv:"{L["rv"]}",rvp:"{L["rvp"]}",rvw:"{L["rvw"]}",rve:"{L["rve"]}",rvn:"{L["rvn"]}",rvs:"{L["rvs"]}",rvd:"{L["rvd"]}",rvdc:"{L["rvdc"]}"}};
window._reviews={{}};
function _rvBadgeHTML(label){{
  if(label==='passed')return '<span class="rv-badge rv-passed">\\u2713 '+_rvL.rvp+'</span>';
  if(label==='warning')return '<span class="rv-badge rv-warning">! '+_rvL.rvw+'</span>';
  if(label==='error')return '<span class="rv-badge rv-error">\\u2717 '+_rvL.rve+'</span>';
  return '';
}}
function _rvLabelIcon(label){{
  if(label==='passed')return '\\u2713 '+_rvL.rvp;
  if(label==='warning')return '! '+_rvL.rvw;
  if(label==='error')return '\\u2717 '+_rvL.rve;
  return label;
}}
function _rvRenderSection(key){{
  const el=document.getElementById('rv-'+key);
  if(!el)return;
  const rev=window._reviews[key];
  let h='<div class="rv-label">\\u2500\\u2500 '+_rvL.rv+' \\u2500\\u2500</div>';
  const editing=window._rvEditing&&window._rvEditing[key];
  if(rev&&!editing){{
    h+='<div class="rv-existing">';
    h+=_rvBadgeHTML(rev.label);
    if(rev.note)h+=' <span class="rv-note">&ldquo;'+rev.note.replace(/</g,'&lt;').replace(/>/g,'&gt;')+'&rdquo;</span>';
    if(rev.time)h+=' <span class="rv-time">'+rev.time+'</span>';
    h+=' <button class="rv-edit" onclick="rvEdit(\\x27'+key+'\\x27)">Edit</button>';
    h+=' <button class="rv-del" data-key="'+key+'" onclick="rvDel(this)">'+_rvL.rvd+'</button>';
    h+='</div>';
  }}else{{
    const prefill=rev||{{}};
    const sel=prefill.label||'passed';
    h+='<div class="rv-form">';
    h+='<select class="rv-select s-'+sel+'" id="rvs-'+key+'" onchange="this.className=\\x27rv-select s-\\x27+this.value">';
    h+='<option value="passed" style="color:var(--ok)"'+(sel==='passed'?' selected':'')+'>\\u2705 '+_rvL.rvp+'</option>';
    h+='<option value="warning" style="color:var(--wn)"'+(sel==='warning'?' selected':'')+'>\\u26a0\\ufe0f '+_rvL.rvw+'</option>';
    h+='<option value="error" style="color:var(--fl)"'+(sel==='error'?' selected':'')+'>\\u274c '+_rvL.rve+'</option>';
    h+='</select>';
    h+='<input class="rv-input" id="rvi-'+key+'" placeholder="'+_rvL.rvn+'" value="'+(prefill.note||'').replace(/"/g,'&quot;')+'" onkeydown="if(event.key===\\x27Enter\\x27)rvSubmit(\\x27'+key+'\\x27)">';
    h+='<button class="rv-submit" onclick="rvSubmit(\\x27'+key+'\\x27)">'+(rev?'Update':_rvL.rvs)+'</button>';
    if(rev)h+=' <button class="rv-del" style="font-size:12px" onclick="rvEditCancel(\\x27'+key+'\\x27)">Cancel</button>';
    h+='</div>';
  }}
  el.innerHTML=h;
}}
function _rvRenderBadge(key){{
  const el=document.getElementById('rvb-'+key);
  if(!el)return;
  const rev=window._reviews[key];
  el.innerHTML=rev?_rvBadgeHTML(rev.label):'';
}}
function _rvUpdateCard(key){{
  const card=document.getElementById('r-'+key);
  if(!card)return;
  const rev=window._reviews[key];
  card.dataset.reviewed=rev?'1':'0';
  _rvRenderBadge(key);
  _rvRenderSection(key);
}}
function _rvUpdateCounts(){{
  const total=document.querySelectorAll('.rc').length;
  const n=Object.keys(window._reviews).length;
  const fbR=document.getElementById('fb-reviewed');
  const fbU=document.getElementById('fb-unreviewed');
  if(fbR)fbR.textContent='{L["fr"]} ('+n+')';
  if(fbU)fbU.textContent='{L["fu"]} ('+(total-n)+')';
}}
function rvSubmit(key){{
  const sel=document.getElementById('rvs-'+key);
  const inp=document.getElementById('rvi-'+key);
  if(!sel)return;
  const label=sel.value,note=inp?inp.value:'';
  fetch('/api/reviews',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{key:key,label:label,note:note}})}})
    .then(r=>r.json()).then(d=>{{
      if(d.ok){{
        window._reviews[key]=d.review;
        delete window._rvEditing[key];
        _rvUpdateCard(key);
        _rvUpdateCounts();
      }}
    }});
}}
window._rvEditing={{}};
function rvEdit(key){{
  window._rvEditing[key]=true;
  _rvRenderSection(key);
}}
function rvEditCancel(key){{
  delete window._rvEditing[key];
  _rvRenderSection(key);
}}
function rvDel(btn){{
  const key=btn.dataset.key;
  if(!btn.classList.contains('rv-confirm')){{
    btn.classList.add('rv-confirm');
    btn.textContent=_rvL.rvdc;
    return;
  }}
  fetch('/api/reviews/delete',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{key:key}})}})
    .then(r=>r.json()).then(d=>{{
      if(d.ok){{
        delete window._reviews[key];
        _rvUpdateCard(key);
        _rvUpdateCounts();
      }}
    }});
}}
function exportReviews(){{
  fetch('/api/reviews/export',{{method:'POST'}})
    .then(r=>r.blob()).then(blob=>{{
      const a=document.createElement('a');
      a.href=URL.createObjectURL(blob);
      a.download='citelint-review.md';
      document.body.appendChild(a);a.click();a.remove();
    }});
}}
// Load reviews on page load
(function(){{
  fetch('/api/reviews').then(r=>r.json()).then(d=>{{
    window._reviews=d||{{}};
    document.querySelectorAll('.rc[data-key]').forEach(c=>{{
      const k=c.dataset.key;
      if(window._reviews[k])c.dataset.reviewed='1';
      _rvRenderBadge(k);
      _rvRenderSection(k);
    }});
    _rvUpdateCounts();
  }}).catch(()=>{{}});
}})();
// Live reload
(function(){{let g=-1;setInterval(()=>{{fetch('/api/reload').then(r=>r.json()).then(d=>{{if(g>=0&&d.generation!==g)location.reload();g=d.generation;}}).catch(()=>{{}});}},2000);}})();
// S2 API key banner
(function(){{
  const kb=document.getElementById('kb');
  function renderKey(configured,key){{
    if(configured){{
      kb.className='kb ok';
      kb.innerHTML='<b>Semantic Scholar API key: </b><code>'+key+'</code>'
        +'<div class="kd">Search & Verify will use this key. To change it, edit S2_API_KEY in your shell config.</div>';
    }}else{{
      kb.className='kb';
      kb.innerHTML='<b>Semantic Scholar API key not configured</b><br>'
        +'Search & Verify works without it, but is rate-limited (~10 searches/min).<br><br>'
        +'<a href="https://www.semanticscholar.org/product/api" target="_blank">Apply for a free key</a> (takes ~1 min to apply, may take a few hours to receive).<br>'
        +'Already have a key? Paste it here: '
        +'<input id="ki" placeholder="paste your S2 API key" onkeydown="if(event.key===String.fromCharCode(69,110,116,101,114))saveKey()">'
        +'<button onclick="saveKey()">Save</button>';
    }}
  }}
  window.saveKey=function(){{
    const v=document.getElementById('ki').value.trim();
    if(!v)return;
    fetch('/api/set-key',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{key:v}})}})
      .then(r=>r.json()).then(d=>{{
        if(d.ok){{
          renderKey(true,v);
          if(d.persisted)kb.innerHTML+='<div class="kd" style="color:var(--ok)">Key saved to ~/.zshrc — will persist across restarts.</div>';
        }}
      }});
  }};
  fetch('/api/key-status').then(r=>r.json()).then(d=>renderKey(d.configured,d.key)).catch(()=>{{kb.style.display='none';}});
}})();
// BibGuard progress banner
(function(){{
  const bb=document.getElementById('bg-banner');
  let done=false;
  function poll(){{
    fetch('/api/bibguard-status').then(r=>r.json()).then(d=>{{
      if(d.status==='running'){{
        bb.style.display='block';
        bb.className='kb';
        bb.innerHTML='<span class="sp"></span> BibGuard checking '+d.total+' entries against online databases... <b>'+d.elapsed+'s</b>'
          +'<div class="kd">Page will auto-refresh when results are ready. You can keep browsing.</div>';
      }}else if(d.status==='done'||d.status==='failed'){{
        done=true;
        bb.style.display='none';
      }}else{{
        bb.style.display='none';
      }}
      if(!done)setTimeout(poll,2000);
    }}).catch(()=>{{bb.style.display='none';}});
  }}
  poll();
}})();
</script></body></html>'''
